site_name: Drift Docs

nav:
    - 'Starting Location': 'index.md'
    - 'Drift Edit':
      - 'Modes':
        - 'Cliffs/Ramps': 'driftEdit/modes/cliffsRamps.md'
        - 'Height Map': 'driftEdit/modes/heightMap.md'
        - 'Spawns': 'driftEdit/modes/spawns.md'
        - 'Tex Splatting': 'driftEdit/modes/texSplatting.md'
        - 'Units': 'driftEdit/modes/units.md'
        - 'Triangles': 'driftEdit/modes/triangles.md'
        - 'Triangle Groups': 'driftEdit/modes/triangleGroups.md'
        - 'Decals': 'driftEdit/modes/decals.md'
        - 'Unbuildable': 'driftEdit/modes/unbuildable.md'
        - 'Footprints': 'driftEdit/modes/footprints.md'
        - 'Tex Layers': 'driftEdit/modes/texLayers.md'
        - 'Locations': 'driftEdit/modes/locations.md'
      - Other:
        - 'Map Settings': 'driftEdit/other/mapSettings.md'
        - 'Scene Settings': 'driftEdit/other/sceneSettings.md'
        - '[1v1] Spawns': 'driftEdit/other/1v1Spawns.md'
        - '[Teams] Spawns': 'driftEdit/other/teamSpawns.md'
        - 'Data Editor': 'driftEdit/other/dataEditor.md'
        - 'Script': 'driftEdit/other/script.md'
        - '[Custom] Forces': 'driftEdit/other/forces.md'
        - '[Custom] Tags': 'driftEdit/other/tags.md'
        - '[Custom] Tags Per Force': 'driftEdit/other/tagsPerForce.md'
      - 'Side Controls': 'driftEdit/sideControls.md'
      - 'Misc':
        - 'Text Encoding': 'driftEdit/misc/textEncoding.md'
    - 'Drift Script':
        - 'Introduction': 'driftScript/intro.md'
        - 'Script Entry Points': 'driftScript/scriptEntryPoints.md'
        - 'Identifiers': 'driftScript/identifiers.md'
        - 'Built-in Types': 'driftScript/builtinTypes.md'
        - 'Math Library': 'driftScript/math.md'
        - 'Functions': 'driftScript/functions.md'
        - 'Enumerations': 'driftScript/enumerations.md'
        - 'Event Queue': 'driftScript/eventQueue.md'
        - 'VSCode Syntax Highlighting': 'driftScript/vscodeSyntaxHighlighting.md'
        - 'Examples and Gotchyas': 'driftScript/gotchyas.md'
        - 'More Examples..': 'driftScript/examples.md'
    - 'Drift Shader':
        - 'Introduction': 'driftShader/intro.md'

theme:
    name: material
    highlightjs: false  # disable highlight.js
    palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

plugins:
  - search
  - macros

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true   # enable Pygments highlighting
      guess_lang: false    # prevent guessing
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - sq_lexer